/**
 * String Pool — bidirectional string ↔ i32 ID mapping.
 *
 * In zero-allocation ECS architectures, components must have fixed, predictable size in binary memory (ArrayBuffer).
 * Since strings have variable length, the ECS stores only the i32 ID generated by this dictionary.
 * Individual components that reference strings use the ID, not the string itself.
 */
export class StringPool {
  private strToId = new Map<string, number>();
  private idToStr = new Map<number, string>();
  private nextId = 1;

  /**
   * Get or create a unique ID for a string.
   *
   * @param str The string to intern
   * @returns A unique 32-bit signed integer ID for this string
   */
  public intern(str: string): number {
    let id = this.strToId.get(str);
    if (id === undefined) {
      id = this.nextId++;
      this.strToId.set(str, id);
      this.idToStr.set(id, str);
    }
    return id;
  }

  /**
   * Retrieve the string associated with an ID.
   *
   * @param id The string ID
   * @returns The string, or empty string if not found
   */
  public get(id: number): string {
    return this.idToStr.get(id) ?? '';
  }

  /**
   * Clear all interned strings. Useful for tests or scene transitions.
   */
  public clear(): void {
    this.strToId.clear();
    this.idToStr.clear();
    this.nextId = 1;
  }
}

/** Global singleton StringPool instance for the engine. */
export const GlobalStringPool = new StringPool();
