import { UIComponent, definePrefab } from '@gwenengine/core';
import type { EntityId } from '@gwenengine/core';
import { BlockVisual } from '../components';

/**
 * Visual block entity used by the showcase scene.
 * Gameplay collision stays in the static geometry generated by the kit helper.
 */
export const BlockPrefab = definePrefab({
  name: 'Block',
  create(api, x: number, y: number, w = 32, h = 32): EntityId {
    const id = api.createEntity();
    api.addComponent(id, BlockVisual, { x, y, w, h });
    api.addComponent(id, UIComponent, { uiName: 'BlockUI' });
    return id;
  },
});
