/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_jsentityid_free: (a: number, b: number) => void;
export const jsentityid_index: (a: number) => number;
export const jsentityid_generation: (a: number) => number;
export const __wbg_engine_free: (a: number, b: number) => void;
export const engine_new: (a: number) => number;
export const engine_create_entity: (a: number) => number;
export const engine_delete_entity: (a: number, b: number, c: number) => number;
export const engine_count_entities: (a: number) => number;
export const engine_is_alive: (a: number, b: number, c: number) => number;
export const engine_register_component_type: (a: number) => number;
export const engine_add_component: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const engine_remove_component: (a: number, b: number, c: number, d: number) => number;
export const engine_has_component: (a: number, b: number, c: number, d: number) => number;
export const engine_get_component_raw: (a: number, b: number, c: number, d: number, e: number) => void;
export const engine_update_entity_archetype: (a: number, b: number, c: number, d: number) => void;
export const engine_query_entities: (a: number, b: number, c: number, d: number) => void;
export const engine_tick: (a: number, b: number) => void;
export const engine_frame_count: (a: number) => bigint;
export const engine_delta_time: (a: number) => number;
export const engine_total_time: (a: number) => number;
export const engine_should_sleep: (a: number) => number;
export const engine_sleep_time_ms: (a: number) => number;
export const engine_reset_frame: (a: number) => void;
export const engine_stats: (a: number, b: number) => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number) => void;
