import type { EngineConfig, WasmPlugin, TsPlugin, GwenWasmPlugin } from '../types';
import type { GwenPlugin, MergeAllProvides } from '../plugin-system/plugin';
import { Engine } from '../engine/engine';
import { SceneManager } from '../api/scene';
import { SharedMemoryManager } from '../wasm/shared-memory';
import { PluginDataBus } from '../wasm/plugin-data-bus';
import { getWasmBridge } from '../engine/wasm-bridge';
export { ConfigBuilder } from './config-builder';

/**
 * Default engine configuration - Pure logic, no rendering concerns
 * Matches Nuxt-like config pattern with wasm/ts plugin separation
 */
export const defaultConfig: EngineConfig = {
  maxEntities: 5000,
  targetFPS: 60,
  debug: false,
  enableStats: true,
  wasmPlugins: [],
  tsPlugins: [],
};

/**
 * Merge user config with defaults
 * Handles both new (wasm/ts) plugin formats
 */
export function mergeConfigs(defaults: EngineConfig, user: Partial<EngineConfig>): EngineConfig {
  return {
    ...defaults,
    ...user,
    wasmPlugins: [...(defaults.wasmPlugins || []), ...(user.wasmPlugins || [])],
    tsPlugins: [...(defaults.tsPlugins || []), ...(user.tsPlugins || [])],
  };
}

/**
 * Typed result of defineConfig() — exposes the inferred ServiceMap and HooksMap from plugins.
 *
 * `Services` is the intersection of `provides` from all declared plugins.
 * `Hooks` is the intersection of `providesHooks` from all declared plugins.
 */
export interface TypedEngineConfig<
  Services extends Record<string, unknown>,
  Hooks extends Record<string, any> = Record<string, never>,
> {
  readonly _services: Services; // phantom type — never read at runtime
  readonly _hooks: Hooks; // phantom type — never read at runtime
  readonly maxEntities?: number;
  readonly targetFPS?: number;
  readonly debug?: boolean;
  readonly enableStats?: boolean;
  readonly tsPlugins?: TsPlugin[];
  readonly wasmPlugins?: WasmPlugin[];
  /**
   * Scene to load at engine startup.
   *
   * If not specified, prepare() looks for scenes named 'Main', 'MainMenu',
   * or 'Boot', otherwise uses the first detected scene.
   *
   * @example mainScene: 'MainMenu'
   */
  readonly mainScene?: string;
  /**
   * Automatic scene loading from src/scenes/.
   *
   * - `'auto'` (default): CLI scans src/scenes/*.ts during prepare.
   *   File .gwen/scenes.ts is generated with imports + registrations.
   * - `false`: disabled, manage your scenes manually in main.ts.
   */
  readonly scenes?: 'auto' | false;
  /**
   * Configuration for HTML generated by GWEN.
   * If index.html is missing from the project, GWEN auto-generates it.
   *
   * @example
   * html: {
   *   title: 'My Game',
   *   canvasId: 'game-canvas',
   *   canvasWidth: 800,
   *   canvasHeight: 600,
   *   background: '#000',
   * }
   */
  readonly html?: {
    /** Page title. Default: project name */
    title?: string;
    /** Page background color. Default: '#000' */
    background?: string;
  };
}

/**
 * Définit la configuration d'un projet GWEN avec inférence complète des services et hooks.
 *
 * Les services et hooks exposés par chaque plugin sont automatiquement fusionnés dans
 * `TypedEngineConfig<Services, Hooks>`, ce qui permet à `api.services.get()` et `api.hooks.hook()`
 * d'être fortement typés partout dans le projet.
 *
 * ```typescript
 * // gwen.config.ts
 * export default defineConfig({
 *   tsPlugins: [new InputPlugin(), new AudioPlugin()],
 *   wasmPlugins: [Physics2D({ gravity: 9.81 })],
 *   maxEntities: 10_000,
 *   targetFPS: 60,
 * });
 *
 * // In a system / plugin — fully typed after gwen prepare, no annotation needed
 * onInit(api) {
 *   const kb = api.services.get('keyboard'); // → KeyboardInput ✅
 *   const au = api.services.get('audio');    // → AudioManager  ✅
 *   api.hooks.hook('input:keyDown', (key) => {}); // ✅ Type-safe
 *   api.hooks.hook('physics:collision', (event) => {}); // ✅ Type-safe
 * }
 * ```
 *
 * @param config Project configuration. `tsPlugins` accepts any plugin
 *   implementing `GwenPlugin` (with `provides` and `providesHooks`) or `TsPlugin` (untyped).
 */
export function defineConfig<
  const TsPlugins extends readonly GwenPlugin[],
  const WasmPlugins extends readonly GwenWasmPlugin[],
>(config: {
  engine?: { maxEntities?: number; targetFPS?: number; debug?: boolean; enableStats?: boolean };
  tsPlugins?: [...TsPlugins];
  wasmPlugins?: [...WasmPlugins];
  maxEntities?: number;
  targetFPS?: number;
  debug?: boolean;
  enableStats?: boolean;
  mainScene?: string;
  scenes?: 'auto' | false;
  html?: {
    title?: string;
    background?: string;
  };
}): TypedEngineConfig<
  MergeAllProvides<TsPlugins, WasmPlugins>,
  import('../plugin-system/plugin').MergeAllHooks<TsPlugins>
> {
  return config as unknown as TypedEngineConfig<
    MergeAllProvides<TsPlugins, WasmPlugins>,
    import('../plugin-system/plugin').MergeAllHooks<TsPlugins>
  >;
}

/**
 * Create an Engine and SceneManager from a TypedEngineConfig.
 *
 * Instantiates the engine, registers all plugins declared in `config.plugins`
 * and returns `{ engine, scenes }` ready to use.
 *
 * The `sceneLoader` is auto-generated by `gwen prepare` in
 * `.gwen/scenes.ts`. It receives the `SceneManager` and registers all
 * scenes found in `src/scenes/`. If `scenes: false` in config,
 * pass `undefined` and manage your scenes manually.
 *
 * ```typescript
 * // main.ts — generated by create-gwen-app
 * import { initWasm, createEngine } from '@gwen/engine-core';
 * import gwenConfig from '../gwen.config';
 * import { registerScenes, mainScene } from '../.gwen/scenes';
 *
 * await initWasm();
 * const { engine, scenes } = createEngine(gwenConfig, registerScenes, mainScene);
 * engine.start();
 * ```
 */
/**
 * Create an Engine and SceneManager from a TypedEngineConfig.
 *
 * **This function is async** — it awaits initialization of each WASM plugin
 * declared in `config.wasmPlugins` before returning.
 *
 * ```typescript
 * // main.ts
 * await initWasm();
 * const { engine, scenes } = await createEngine(gwenConfig, registerScenes, mainScene);
 * engine.start();
 * ```
 */
export async function createEngine(
  config: TypedEngineConfig<Record<string, unknown>>,
  sceneLoader?: (scenes: SceneManager) => void,
  mainScene?: string,
): Promise<{
  engine: Engine;
  scenes: SceneManager;
}> {
  const raw = config as unknown as EngineConfig & {
    tsPlugins?: TsPlugin[];
    wasmPlugins?: GwenWasmPlugin[];
    mainScene?: string;
    engine?: Partial<EngineConfig>;
  };
  const engineOpts = raw.engine ?? {};
  const maxEntities = engineOpts.maxEntities ?? raw.maxEntities ?? 5000;

  const engine = new Engine({
    maxEntities,
    targetFPS: engineOpts.targetFPS ?? raw.targetFPS ?? 60,
    debug: engineOpts.debug ?? raw.debug ?? false,
    enableStats: engineOpts.enableStats ?? raw.enableStats ?? true,
  });

  const api = engine.getAPI();
  const scenes = new SceneManager();
  engine.registerSystem(scenes);

  // ── WASM plugins ───────────────────────────────────────────────────────────
  const wasmPlugins: GwenWasmPlugin[] = raw.wasmPlugins ?? [];

  if (wasmPlugins.length > 0) {
    const bridge = getWasmBridge();

    if (!bridge.isActive()) {
      throw new Error(
        '[GWEN] createEngine(): WASM core not initialized.\n' +
          'Call `await initWasm()` before `await createEngine()`.',
      );
    }

    // Warn if the browser context is not cross-origin isolated
    // (not a hard requirement for our pointer-based bridge, but good practice)
    if (typeof crossOriginIsolated !== 'undefined' && !crossOriginIsolated) {
      console.warn(
        '[GWEN] Cross-origin isolation is inactive (crossOriginIsolated = false).\n' +
          'Add the following HTTP headers to unlock the full WASM plugin performance:\n' +
          '  Cross-Origin-Opener-Policy: same-origin\n' +
          '  Cross-Origin-Embedder-Policy: require-corp\n' +
          'The engine will still work, but SharedArrayBuffer will not be available.',
      );
    }

    // Allocate the shared buffer in gwen-core's WASM linear memory.
    // The manager is kept on the Engine so _tick() can call checkSentinels() in debug mode.
    const sharedMemory = SharedMemoryManager.create(bridge, maxEntities);
    engine._setSharedMemoryPtr(sharedMemory.getTransformRegion().ptr, maxEntities, sharedMemory);

    // ── Plugin Data Bus ────────────────────────────────────────────────────
    // Allocate JS-native ArrayBuffers for each channel declared by WASM plugins.
    // These buffers are independent of gwen-core's linear memory — a memory.grow()
    // event in gwen-core has zero effect on them.
    const pluginDataBus = new PluginDataBus();
    for (const plugin of wasmPlugins) {
      if (plugin.channels) {
        for (const channel of plugin.channels) {
          pluginDataBus.allocate(plugin.id, channel, maxEntities);
        }
      }
    }
    pluginDataBus.writeSentinels();
    engine._setPluginDataBus(pluginDataBus);

    // ── Phase 1: fetch all WASM binaries in parallel ──────────────────────
    // Network downloads can overlap — we only need their order to match
    // declaration order for the sequential memory allocation below.
    //
    // Each plugin's onInit() is intentionally split into two phases:
    //   Phase 1: fetch the .wasm binary (parallel — pure network I/O)
    //   Phase 2: allocate region, init Rust plugin, register services (sequential)
    //
    // This avoids the race condition that would arise from running onInit()
    // fully in parallel: allocateRegion() mutates `usedBytes` and is not
    // concurrency-safe.
    //
    // Plugins that do not use loadWasmPlugin() internally (e.g. pure-TS adapters
    // that implement GwenWasmPlugin) still go through Phase 2 sequentially.
    if (raw.debug) {
      console.log(`[GWEN] Fetching ${wasmPlugins.length} WASM plugin(s) in parallel…`);
    }

    const pluginModules = await Promise.all(
      wasmPlugins.map(async (plugin) => {
        // Kick off the WASM binary fetch for this plugin.
        // Plugins that implement the optional `_prefetch()` hook use it to
        // download their .wasm early; others will fetch lazily inside onInit().
        await (plugin as GwenWasmPlugin & { _prefetch?(): Promise<void> })._prefetch?.();
        return plugin;
      }),
    );

    // ── Phase 2: allocate regions and initialize sequentially ─────────────
    // Memory allocation and service registration must happen in order so that
    // region offsets are deterministic and services are registered before any
    // subsequent plugin's onInit() might try to access them.
    for (const plugin of pluginModules) {
      // Bus-first plugins set sharedMemoryBytes = 0: no legacy SAB region needed.
      const region =
        plugin.sharedMemoryBytes > 0
          ? sharedMemory.allocateRegion(plugin.id, plugin.sharedMemoryBytes)
          : null;

      await plugin.onInit(bridge, region, api, pluginDataBus);
      engine._registerWasmPlugin(plugin);

      if (raw.debug) {
        const memoryMode = region ? `SAB=${region.byteLength}B` : 'SAB=disabled (DataBus only)';
        console.log(
          `[GWEN] WASM plugin '${plugin.name}' (id='${plugin.id}') initialized — ${memoryMode}`,
        );
      }
    }

    // Write sentinel canaries into the shared buffer now that all regions are
    // allocated. The Rust plugins have not written anything yet at this point,
    // so the sentinel positions are guaranteed to be untouched.
    sharedMemory._writeSentinels(bridge);

    if (raw.debug) {
      console.log(
        `[GWEN] Shared buffer: ${sharedMemory.allocatedBytes}B used / ` +
          `${sharedMemory.capacityBytes}B total — sentinels written`,
      );
    }
  }

  // ── TypeScript plugins ─────────────────────────────────────────────────────
  const plugins: TsPlugin[] = raw.tsPlugins ?? [];
  for (const plugin of plugins) {
    engine.registerSystem(plugin);
  }

  // ── Scene loading ──────────────────────────────────────────────────────────
  if (sceneLoader) {
    sceneLoader(scenes);
    const resolvedMain = mainScene ?? raw.mainScene ?? resolveMainScene(scenes);
    if (resolvedMain) {
      try {
        scenes.loadSceneImmediate(resolvedMain, api);
      } catch {
        console.warn(`[GWEN] mainScene '${resolvedMain}' not found — no scene loaded.`);
      }
    }
  }

  return { engine, scenes };
}

/**
 * Resolve the main scene by convention among registered scenes.
 * Searches in order: 'Main', 'MainMenu', 'Boot', then first.
 */
function resolveMainScene(scenes: SceneManager): string | null {
  const candidates = ['Main', 'MainMenu', 'Boot'];
  for (const name of candidates) {
    if (scenes.hasScene(name)) return name;
  }
  // Fallback: first registered scene
  const all = scenes.getSceneNames();
  return all.length > 0 ? all[0] : null;
}

/**
 * Extrait le type `Services` d'une `TypedEngineConfig`.
 *
 * ```typescript
 * const config = defineConfig({ plugins: [new InputPlugin()] });
 * export type GwenServices = GwenConfigServices<typeof config>;
 * // → { keyboard: KeyboardInput; mouse: MouseInput; ... }
 * ```
 */
export type GwenConfigServices<C> =
  C extends TypedEngineConfig<infer S, any> ? S : Record<string, unknown>;

/**
 * Extrait le type `Hooks` d'une `TypedEngineConfig`.
 *
 * ```typescript
 * const config = defineConfig({ plugins: [new InputPlugin(), new Physics2DPlugin()] });
 * export type GwenHooks = GwenConfigHooks<typeof config>;
 * // → GwenHooks & InputPluginHooks & Physics2DHooks
 * ```
 */
export type GwenConfigHooks<C> =
  C extends TypedEngineConfig<any, infer H> ? H : import('../hooks').GwenHooks;
