import type { EngineConfig, WasmPlugin, TsPlugin } from '../types';
import type { AnyGwenPlugin, MergeProvides } from '../plugin-system/plugin';
import { Engine } from '../engine/engine';
import { SceneManager } from '../api/scene';
export { ConfigBuilder } from './config-builder';

// ...existing code...

/**
 * Default engine configuration - Pure logic, no rendering concerns
 * Matches Nuxt-like config pattern with wasm/ts plugin separation
 */
export const defaultConfig: EngineConfig = {
  maxEntities: 5000,
  targetFPS: 60,
  debug: false,
  enableStats: true,
  wasmPlugins: [],
  tsPlugins: [],
};

/**
 * Merge user config with defaults
 * Handles both new (wasm/ts) plugin formats
 */
export function mergeConfigs(defaults: EngineConfig, user: Partial<EngineConfig>): EngineConfig {
  return {
    ...defaults,
    ...user,
    wasmPlugins: [...(defaults.wasmPlugins || []), ...(user.wasmPlugins || [])],
    tsPlugins: [...(defaults.tsPlugins || []), ...(user.tsPlugins || [])],
  };
}

/**
 * Typed result of defineConfig() — exposes the inferred ServiceMap from plugins.
 *
 * `Services` is the intersection of `provides` from all declared plugins.
 */
export interface TypedEngineConfig<Services extends Record<string, unknown>> {
  readonly _services: Services; // phantom type — never read at runtime
  readonly maxEntities?: number;
  readonly targetFPS?: number;
  readonly debug?: boolean;
  readonly enableStats?: boolean;
  readonly tsPlugins?: TsPlugin[];
  readonly wasmPlugins?: WasmPlugin[];
  /**
   * Scene to load at engine startup.
   *
   * If not specified, prepare() looks for scenes named 'Main', 'MainMenu',
   * or 'Boot', otherwise uses the first detected scene.
   *
   * @example mainScene: 'MainMenu'
   */
  readonly mainScene?: string;
  /**
   * Automatic scene loading from src/scenes/.
   *
   * - `'auto'` (default): CLI scans src/scenes/*.ts during prepare.
   *   File .gwen/scenes.ts is generated with imports + registrations.
   * - `false`: disabled, manage your scenes manually in main.ts.
   */
  readonly scenes?: 'auto' | false;
  /**
   * Configuration for HTML generated by GWEN.
   * If index.html is missing from the project, GWEN auto-generates it.
   *
   * @example
   * html: {
   *   title: 'My Game',
   *   canvasId: 'game-canvas',
   *   canvasWidth: 800,
   *   canvasHeight: 600,
   *   background: '#000',
   * }
   */
  readonly html?: {
    /** Page title. Default: project name */
    title?: string;
    /** Page background color. Default: '#000' */
    background?: string;
  };
}

/**
 * Définit la configuration d'un projet GWEN avec inférence complète des services.
 *
 * Les services exposés par chaque plugin sont automatiquement fusionnés dans
 * `TypedEngineConfig<Services>`, ce qui permet à `api.services.get()` d'être
 * fortement typé partout dans le projet.
 *
 * ```typescript
 * // gwen.config.ts
 * export default defineConfig({
 *   tsPlugins: [new InputPlugin(), new AudioPlugin()],
 *   wasmPlugins: [Physics2D({ gravity: 9.81 })],
 *   maxEntities: 10_000,
 *   targetFPS: 60,
 * });
 *
 * // In a system / plugin
 * onInit(api: EngineAPI<GwenServices>) {
 *   const kb = api.services.get('keyboard'); // → KeyboardInput ✅
 *   const au = api.services.get('audio');    // → AudioManager  ✅
 * }
 * ```
 *
 * @param config Project configuration. `tsPlugins` accepts any plugin
 *   implementing `GwenPlugin` (with `provides`) or `TsPlugin` (untyped).
 */
export function defineConfig<const Plugins extends readonly AnyGwenPlugin[]>(config: {
  /** Nuxt-like shorthand: engine: { maxEntities, targetFPS, debug } */
  engine?: { maxEntities?: number; targetFPS?: number; debug?: boolean; enableStats?: boolean };
  tsPlugins?: [...Plugins];
  wasmPlugins?: WasmPlugin[];
  maxEntities?: number;
  targetFPS?: number;
  debug?: boolean;
  enableStats?: boolean;
  /**
   * Scene to load at startup.
   * If unspecified, searches for 'Main', 'MainMenu' or 'Boot', then first scene.
   */
  mainScene?: string;
  /**
   * Scene loading mode.
   * - `'auto'` (default): scan src/scenes/*.ts during `gwen prepare`.
   * - `false`: disabled, manage manually in main.ts.
   */
  scenes?: 'auto' | false;
  html?: {
    title?: string;
    background?: string;
  };
}): TypedEngineConfig<MergeProvides<Plugins>> {
  return config as unknown as TypedEngineConfig<MergeProvides<Plugins>>;
}

/**
 * Create an Engine and SceneManager from a TypedEngineConfig.
 *
 * Instantiates the engine, registers all plugins declared in `config.plugins`
 * and returns `{ engine, scenes }` ready to use.
 *
 * The `sceneLoader` is auto-generated by `gwen prepare` in
 * `.gwen/scenes.ts`. It receives the `SceneManager` and registers all
 * scenes found in `src/scenes/`. If `scenes: false` in config,
 * pass `undefined` and manage your scenes manually.
 *
 * ```typescript
 * // main.ts — generated by create-gwen-app
 * import { initWasm, createEngine } from '@gwen/engine-core';
 * import gwenConfig from '../gwen.config';
 * import { registerScenes, mainScene } from '../.gwen/scenes';
 *
 * await initWasm();
 * const { engine, scenes } = createEngine(gwenConfig, registerScenes, mainScene);
 * engine.start();
 * ```
 */
export function createEngine(
  config: TypedEngineConfig<Record<string, unknown>>,
  sceneLoader?: (scenes: SceneManager) => void,
  mainScene?: string,
): {
  engine: Engine;
  scenes: SceneManager;
} {
  const raw = config as unknown as EngineConfig & {
    tsPlugins?: TsPlugin[];
    mainScene?: string;
    engine?: Partial<EngineConfig>;
  };
  const engineOpts = raw.engine ?? {};
  const engine = new Engine({
    maxEntities: engineOpts.maxEntities ?? raw.maxEntities ?? 5000,
    targetFPS: engineOpts.targetFPS ?? raw.targetFPS ?? 60,
    debug: engineOpts.debug ?? raw.debug ?? false,
    enableStats: engineOpts.enableStats ?? raw.enableStats ?? true,
  });

  const scenes = new SceneManager();
  engine.registerSystem(scenes);

  // Register plugins declared in config.tsPlugins
  const plugins: TsPlugin[] = raw.tsPlugins ?? [];
  for (const plugin of plugins) {
    engine.registerSystem(plugin);
  }

  // Load scenes via loader generated by prepare (if provided)
  if (sceneLoader) {
    sceneLoader(scenes);

    // Resolve main scene:
    // 1. Explicit parameter passed to createEngine
    // 2. mainScene in config
    // 3. Convention: 'Main', 'MainMenu', 'Boot'
    // 4. Fallback: first registered scene
    const resolvedMain = mainScene ?? raw.mainScene ?? resolveMainScene(scenes);

    if (resolvedMain) {
      try {
        scenes.loadSceneImmediate(resolvedMain, engine.getAPI());
      } catch {
        console.warn(`[GWEN] mainScene '${resolvedMain}' not found — no scene loaded.`);
      }
    }
  }

  return { engine, scenes };
}

/**
 * Resolve the main scene by convention among registered scenes.
 * Searches in order: 'Main', 'MainMenu', 'Boot', then first.
 */
function resolveMainScene(scenes: SceneManager): string | null {
  const candidates = ['Main', 'MainMenu', 'Boot'];
  for (const name of candidates) {
    if (scenes.hasScene(name)) return name;
  }
  // Fallback: first registered scene
  const all = scenes.getSceneNames();
  return all.length > 0 ? all[0] : null;
}

/**
 * Extrait le type `Services` d'une `TypedEngineConfig`.
 *
 * ```typescript
 * const config = defineConfig({ plugins: [new InputPlugin()] });
 * export type GwenServices = GwenConfigServices<typeof config>;
 * // → { keyboard: KeyboardInput; mouse: MouseInput; ... }
 * ```
 */
export type GwenConfigServices<C> =
  C extends TypedEngineConfig<infer S> ? S : Record<string, unknown>;
