/**
 * Type definitions generation for GWEN projects
 * Generates gwen.d.ts with global type interfaces from config
 */

import * as path from 'node:path';
import fs from 'node:fs/promises';

/**
 * Detect export style of config file (default vs named export)
 */
function detectConfigExportStyle(
  source: string,
): { type: 'default' } | { type: 'named'; name: string } {
  if (/export\s+default\s+defineConfig\s*\(/.test(source)) return { type: 'default' };
  const match = source.match(/export\s+const\s+(\w+)\s*=\s*defineConfig\s*\(/);
  if (match) return { type: 'named', name: match[1] };
  return { type: 'default' }; // fallback
}

/**
 * Generate gwen.d.ts content
 * Provides global type interfaces for the project
 */
export async function generateDts(
  projectDir: string,
  configPath: string,
  typeRefs: string[] = [],
): Promise<string> {
  const relConfig = path
    .relative(path.join(projectDir, '.gwen'), configPath)
    .replace(/\\/g, '/')
    .replace(/\.ts$/, '');

  const source = await fs.readFile(configPath, 'utf-8');
  const exportStyle = detectConfigExportStyle(source);

  const configImport =
    exportStyle.type === 'default'
      ? `import type _cfg from '${relConfig}';`
      : `import type { ${exportStyle.name} as _cfg } from '${relConfig}';`;

  const displayName = exportStyle.type === 'default' ? 'default export' : exportStyle.name;

  // Reference block injected only if plugins need it
  const refBlock =
    typeRefs.length > 0
      ? typeRefs.map((r) => `/// <reference types="${r}" />`).join('\n') + '\n\n'
      : '';

  return `/**
 * GWEN — Global Auto-Generated Types
 * Generated by \`gwen prepare\` — DO NOT MODIFY
 * Source: gwen.config.ts
 *
 * GwenDefaultServices is automatically enriched from the ${displayName}.
 * This makes all define* (defineSystem, defineUI, defineScene, definePrefab)
 * automatically typed — no explicit annotation required.
 */
${refBlock}import type { GwenConfigServices, GwenConfigHooks, EngineAPI } from '@gwen/engine-core';
${configImport}

type _GwenServices = GwenConfigServices<typeof _cfg>;
type _GwenHooks = GwenConfigHooks<typeof _cfg>;

declare global {
  /**
   * Enriches GwenDefaultServices with project services.
   * Used as default generic by EngineAPI, defineUI, etc.
   * No annotation needed in define* functions.
   */
  interface GwenDefaultServices extends _GwenServices {}

  /**
   * Enriches GwenDefaultHooks with plugin hooks.
   */
  interface GwenDefaultHooks extends _GwenHooks {}

  /**
   * Convenience alias for EngineAPI<GwenDefaultServices, GwenDefaultHooks>.
   * Useful for explicit annotation (plugins, third-party libraries).
   */
  type GwenAPI = EngineAPI<GwenDefaultServices, GwenDefaultHooks>;

  /**
   * @deprecated Use GwenAPI or let TypeScript infer automatically.
   * Kept for backward compatibility.
   */
  type GwenServices = _GwenServices;

  const __GWEN_VERSION__: string;
  const __GWEN_DEV__: boolean;
}

export {};
`;
}
